# ~/.config/starship.toml
# bg:#242634

format = "[  ](bg:#33343C fg:#ffffff)$directory($git_branch)$python\n$character"

[directory]
style = "#9cdbfb"
format = "[](bg:$style fg:#33343C)[  $path ](bg:#9cdbfb fg:#292d3e bold)[](fg:$style)"

[git_branch]
style = "#bf94e4"
format = "\b[](bg:$style fg:#9cdbfb)[ $symbol$branch ](bg:$style fg:#292d3e bold)[](fg:$style)"
symbol = " "

[python]
format = '[ (\($virtualenv\))]($style)'
